spring.application.name=back-end

spring.datasource.url=jdbc:postgresql://myappdb.ctkw0us28kyd.ap-south-1.rds.amazonaws.com:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/mapdatabase
spring.datasource.username=varun
spring.datasource.password=SaiVarun
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
aws.s3.bucket=${myapp-user-uploads-varun}
aws.region=${ap-south-1}
jwt.secret=${Xy7!9sA0Lkq2Pr#1Nf8zTgB5hVw6D@Rm}
